In [2]:
import numpy as np

# 1

In [120]:
#Create a NumPy array containing the values [1, 2, 3].

In [125]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [121]:
#Create a 2-dimensional NumPy array.

In [127]:
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [122]:
#Create a 3-dimensional NumPy array.

In [129]:
c = np.array([
    [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],
    [[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]]])
print(c)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


# 2

In [123]:
#check if all elements in the NumPy array [1, 2, 3] are greater than 0.

In [131]:
a = np.array([1,2,3])

print(np.all(a>0))

True


In [124]:
#check if any element in the NumPy array [-1, 0, 1] is greater than 0.

In [134]:
b = np.array([-1,0,1])

print(np.any(b>0))

True


In [10]:
#check if all elements in the NumPy array [[1, 2], [3, 4]] are greater than 0.5.

In [135]:
c = np.array([[1,2],[3,4]])

print(np.all(c>0.5))

True


In [12]:
#Use the appropriate NumPy function to check if any element in the array is true.

In [137]:
d = np.array([True, False, True])

print(np.any(d))

True


# 3

In [69]:
#Write a Python function that takes a 1D numpy array as input and returns a copy of the array with the data type converted to int.

In [143]:
a = np.array([1.3,1.6,2.2])

x = a.astype('int')
print(x)

[1 1 2]


In [144]:
#Write a Python function that takes a 2D numpy array as input and returns a copy of the array 
#with the data type converted to float

In [149]:
b = np.array([1,2,3])

y = b.astype('float')
print(y)

[1. 2. 3.]


In [76]:
#You have an array a of size (3,3) that contains random float values between -1 and 1. 
#create a new array b of the same size, where each element of b is clipped to a range between -0.5 and 0.5. 
#Print both arrays a and b to compare the original and clipped values.

In [197]:
a = np.random.uniform(-1,1,(3,3))
print(a)

b = np.clip(a,-0.5,0.5)
print(b)

[[-0.0458328   0.85010842  0.3217825 ]
 [-0.05653345  0.93793015 -0.12867906]
 [-0.3962936   0.22907169  0.5067217 ]]
[[-0.0458328   0.5         0.3217825 ]
 [-0.05653345  0.5        -0.12867906]
 [-0.3962936   0.22907169  0.5       ]]


In [77]:
#You have an array a of size (5,5) that contains random integer values between 1 and 100.
#create a new array b of the same size, where each element of b is clipped to a range between 
#the 25th and 75th percentile of the values in a. Print both arrays a and b to compare the original and clipped values.

In [206]:
a = np.random.randint(1,101,(5,5))
print(a)

print(f'The 25th percentile of the random range: {np.percentile(a,25)}')
print(f'The 75th percentile of the random range: {np.percentile(a,75)}')

b = np.clip(a,np.percentile(a,25),np.percentile(a,75))
print(b)

[[ 24  71   9  84 100]
 [ 87  84  75   2   3]
 [ 50  34  98  31  14]
 [ 91  44  53  21  22]
 [ 33  18  96  13  92]]
The 25th percentile of the random range: 21.0
The 75th percentile of the random range: 84.0
[[24. 71. 21. 84. 84.]
 [84. 84. 75. 21. 21.]
 [50. 34. 84. 31. 21.]
 [84. 44. 53. 21. 22.]
 [33. 21. 84. 21. 84.]]


# 4

In [78]:
#Create an array a of size (3,3) with random integer values between 0 and 9. create a new array b that is a copy of 
#a (numpy.copy()). Modify the value of an element in b, and then print both a and b to compare the original and 
#modified values. What do you notice about the changes to b?

In [210]:
a = np.random.randint(0,10,(3,3))

b = np.copy(a)
b[1,1] = 99

print(a)
print(b)
#modification to b does not affect the values in a. This is because np.copy() creates a new array with the same shape 
#and data as the original array, but with a new memory location.

[[3 0 2]
 [2 9 5]
 [3 1 1]]
[[ 3  0  2]
 [ 2 99  5]
 [ 3  1  1]]


In [211]:
#Create an array a of size (5,5) with random float values between 0 and 1. create a new array b that is a copy of a. 
#Modify the values of elements in a such that they are all 1.0. Then, print both a and b to confirm that only 
#a was modified and b remains unchanged.

In [227]:
a = np.random.rand(5,5)
print(a)

b = np.copy(a)
print(b)

a[1,1] = 9
print(a)
print(f'b is unchanged:{b}')

[[0.37313804 0.64466292 0.89640918 0.84178044 0.27472591]
 [0.56706606 0.69199144 0.10693686 0.85161939 0.27264167]
 [0.12107449 0.16653154 0.01037735 0.87059633 0.28947867]
 [0.44360833 0.92066713 0.21868071 0.99611785 0.19760816]
 [0.23161666 0.70200288 0.2777557  0.72593    0.87330237]]
[[0.37313804 0.64466292 0.89640918 0.84178044 0.27472591]
 [0.56706606 0.69199144 0.10693686 0.85161939 0.27264167]
 [0.12107449 0.16653154 0.01037735 0.87059633 0.28947867]
 [0.44360833 0.92066713 0.21868071 0.99611785 0.19760816]
 [0.23161666 0.70200288 0.2777557  0.72593    0.87330237]]
[[0.37313804 0.64466292 0.89640918 0.84178044 0.27472591]
 [0.56706606 9.         0.10693686 0.85161939 0.27264167]
 [0.12107449 0.16653154 0.01037735 0.87059633 0.28947867]
 [0.44360833 0.92066713 0.21868071 0.99611785 0.19760816]
 [0.23161666 0.70200288 0.2777557  0.72593    0.87330237]]
b is unchanged:[[0.37313804 0.64466292 0.89640918 0.84178044 0.27472591]
 [0.56706606 0.69199144 0.10693686 0.85161939 0.272641

# 5

In [80]:
#Create an array a of size (4,4) with random integer values between 1 and 10. compute the cumulative product 
#of elements in a along both axes. Print the resulting arrays to compare the intermediate and final results 
#of the cumulative product.

In [231]:
a = np.random.randint(1,11,(4,4))

axis1 = np.cumprod(a,axis=1)
axis2 = np.cumprod(a,axis=0)

print(a)
print(axis1)
print(axis2)

[[ 1  8  8  3]
 [ 7  3  5 10]
 [ 7  7  7  7]
 [ 5  4  8  6]]
[[   1    8   64  192]
 [   7   21  105 1050]
 [   7   49  343 2401]
 [   5   20  160  960]]
[[   1    8    8    3]
 [   7   24   40   30]
 [  49  168  280  210]
 [ 245  672 2240 1260]]


In [81]:
#Create an array a of size (3,3) with random float values between 0 and 1. compute the cumulative product 
#of elements in a along the first axis. Then, use np.sum() to compute the sum of elements in the resulting array. 
#Compare the sum to the final element of the original a.

In [242]:
a = np.random.rand(3,3)
print(a)

axis1 = np.cumprod(a,axis=1)
print(axis1)

col_sum = a[:,2].sum()
print(f'sum of the 3rd column in a: {col_sum}')

[[0.65682465 0.63002653 0.69094575]
 [0.15518027 0.13996479 0.41508213]
 [0.4249166  0.61537327 0.71014853]]
[[0.65682465 0.41381696 0.28592507]
 [0.15518027 0.02171977 0.00901549]
 [0.4249166  0.26148232 0.18569128]]
sum of the 3rd column in a: 1.8161764139071588


# 6

In [243]:
#Create an array a of size (4,4) with random integer values between 1 and 10. compute the cumulative sum of 
#elements in a along both axes. Print the resulting arrays to compare the intermediate and final results of 
#the cumulative sum.

In [248]:
a = np.random.randint(1,11,(4,4))
b = np.cumsum(a,axis=1)
c = np.cumsum(a,axis=0)

print(a)
print(b)
print(c)

[[ 4  6 10  3]
 [ 9  3  3  8]
 [ 3  3  3  1]
 [ 7  5  9  6]]
[[ 4 10 20 23]
 [ 9 12 15 23]
 [ 3  6  9 10]
 [ 7 12 21 27]]
[[ 4  6 10  3]
 [13  9 13 11]
 [16 12 16 12]
 [23 17 25 18]]


In [83]:
#Create an array a of size (3,3) with random float values between 0 and 1. compute the cumulative sum 
#of elements in a along the second axis. Then, use np.mean() to compute the mean of elements in the resulting array. 
#Compare the mean to the final row of the original a, also the final row of the cumulative sum.

In [254]:
a = np.random.rand(3,3)
b = np.cumsum(a,axis=0)

print(a)
print(b)

print(np.sum(a[-1,:]))
print(np.sum(b[-1,:]))

[[0.89244794 0.34226777 0.91247661]
 [0.32109306 0.75156799 0.28460797]
 [0.75646183 0.69446178 0.61020586]]
[[0.89244794 0.34226777 0.91247661]
 [1.213541   1.09383575 1.19708458]
 [1.97000283 1.78829753 1.80729043]]
2.061129463120484
5.565590790859906


# 7

In [255]:
#Create a 2D array a of size (5,5) with random integer values between 1 and 10. extract the main diagonal of 
#a and store it in a 1D array d. Then, compute the sum of elements in d. Compare the sum to the sum of elements 
#in the anti-diagonal of a.

In [276]:
a = np.random.randint(1,11,(5,5))
print(a)
d = np.diagonal(a)
print(f'extracting the maind diagonal of d: {d}')
print(f'sum of the diagonal: {np.sum(d)}')
anti_d = np.diagonal(np.fliplr(a))
print(f'sum of the anti-diagonal: {np.sum(anti_d)}')

[[10  3  8  3  3]
 [ 2  5  7  9  6]
 [ 7  3  6  9  1]
 [ 4  2  6  4  9]
 [ 4 10 10 10 10]]
extracting the maind diagonal of d: [10  5  6  4 10]
sum of the diagonal: 35
sum of the anti-diagonal: 24


# 8

In [86]:
#Create a 4x4 NumPy array filled with the value 7

In [283]:
a = np.full((4,4),7)
print(a)

[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]


In [29]:
#Create a 2D NumPy array of size (3, 5) with all elements initialized to -1

In [284]:
a = np.full((3,4),-1)
print(a)

[[-1 -1 -1 -1]
 [-1 -1 -1 -1]
 [-1 -1 -1 -1]]


In [285]:
#Create a NumPy array of size (2, 2) filled with the value 6. 
#Then create a new array of size (4,1) where the elements are ordered in row-major order.

In [290]:
a = np.full((2,2),6)
print(a)
b = np.array([[3],[5],[1],[0]])

print(np.sort(b,axis=0))

[[6 6]
 [6 6]]
[[0]
 [1]
 [3]
 [5]]


# 9

In [291]:
#Write a function that takes a 2D numpy array as input and flattens it. The function should then return a 
#new 1D numpy array with the same elements as the flattened 2D array.

In [297]:
a = np.random.randint(1,101,(3,5))

print(a)
print(f'Flattened a/2D array: {a.flatten()}')

[[89 87 70 90 37]
 [92 58 57 66 38]
 [28 52  5 70 95]]
Flattened a/2D array: [89 87 70 90 37 92 58 57 66 38 28 52  5 70 95]


In [292]:
#Create a 2D numpy array of shape (2, 3, 4) filled with random integers. flatten the array and then reshape 
#the flattened array into a new array of shape (3, 8).

In [302]:
a = np.random.randint(1,101,(2,3,4))
print(a)
b = a.flatten()
print(b)
c = np.reshape(b,(3,8))
print(c)

[[[44 56 76  7]
  [27 85 34 67]
  [76 62 78 41]]

 [[49 70 61 62]
  [37 28 89 20]
  [36 93 52 67]]]
[44 56 76  7 27 85 34 67 76 62 78 41 49 70 61 62 37 28 89 20 36 93 52 67]
[[44 56 76  7 27 85 34 67]
 [76 62 78 41 49 70 61 62]
 [37 28 89 20 36 93 52 67]]


# 10

In [33]:
#Create a 1D numpy array filled with random integers. retrieve the first element of the array and store it in a variable.

In [309]:
a = np.random.randint(1,11,(1,4))
print(a)
b = a.item(0)
print(f'the first element of the array: {b}')

[[ 1  3 10  6]]
the first element of the array: 1


In [34]:
#Create a 3D numpy array of shape (2, 3, 4) filled with random integers. retrieve a specific element of the 
#array and store it in a variable.

In [315]:
a = np.random.randint(1,101,(2,3,4))
print(a)
b = a.item(12)
print(b)

[[[47 94 61 63]
  [61 30 70 73]
  [95 72  4 83]]

 [[18 52 73 30]
  [90 17 95 91]
  [29 29 38 53]]]
18


# 11

In [35]:
#Given a 2D array arr, find the minimum value in each row and find the maximum value in each column.

In [322]:
a = np.random.randint(101,201,(4,6))
print(a)

column_min = np.min(a, axis=0)
row_min = np.min(a, axis=1)

print(f'minimum value in every column: {column_min}')
print(f'minimum value in every row: {row_min}')

[[180 134 123 110 190 111]
 [149 179 166 185 182 155]
 [148 142 139 151 176 153]
 [173 199 139 199 190 184]]
minimum value in every column: [148 134 123 110 176 111]
minimum value in every row: [110 149 139 139]


In [36]:
#Create a random array of size 10x10 using np.random.rand. find the minimum and maximum values in the entire array.

In [323]:
a = np.random.rand(10,10)
print(f'minimum value of an array a: {np.min(a)}')
print(f'maximum value of an array a: {np.max(a)}')

minimum value of an array a: 0.001411961404731099
maximum value of an array a: 0.9915346382618263


# 12

In [38]:
#Create a numpy array a with random integers between 1 and 10. Calculate the mean of a.

In [339]:
print(f'the mean of a: {np.random.randint(1,11,(3,4)).mean()}')

the mean of a: 4.333333333333333


In [39]:
#Create a 2D numpy array b with random floats between 0 and 1. Calculate the mean of each row and each column.

In [346]:
a = np.random.rand(2,3)
print(a)

print(f'the mean of row1/row2 is: {np.mean(a,axis=1)}')
print(f'the mean of column1/column2 is: {np.mean(a,axis=0)}')

[[0.77028786 0.91036732 0.68417004]
 [0.03646871 0.21672203 0.05603761]]
the mean of row1/row2 is: [0.78827507 0.10307611]
the mean of column1/column2 is: [0.40337828 0.56354467 0.37010382]


In [347]:
#Create a numpy array e of shape (4, 4) with random integers between 1 and 10. 
#Calculate the mean of the elements in the diagonal of e.

In [354]:
e = np.random.randint(1,11,(4,4))
print(e)

d = np.diagonal(e).mean()
print(d)

[[ 2  6  2  4]
 [ 1  3  2  6]
 [ 3  8 10  5]
 [ 3  5  2  5]]
5.0


In [41]:
#Create two numpy arrays h1 and h2 with random integers between 1 and 10 and concatenate them vertically 
#to create a 2D array h. Calculate the mean of each row of h.

In [364]:
h1 = np.random.randint(1,11,5)
h2 = np.random.randint(1,11,5)
print(h1)
print(h2)

h = np.vstack((h1,h2))
print(h)

print(f'the mean of each row of h: {np.mean(h,axis=1)}')

[7 1 3 2 3]
[ 9 10  7  7  5]
the mean of each row of h: [3.2 7.6]


# 13

In [1]:
#Create a NumPy array with some zeros and non-zero elements. find the indices of the non-zero elements.

In [370]:
x = np.array([1,0,4,2,0,0])

print(np.nonzero(x))

(array([0, 2, 3], dtype=int64),)


# 14

In [3]:
#Given a numpy array a, find the product of all its elements Then, replace all the negative elements in a 
#with 1 and again find the product of all the elements in a. Compare the two results.

In [10]:
a = np.array([[1,2,-6],
              [4,-2,-9],
              [12,-15,13]])

print(f'the product of all elements in array a: {np.prod(a)}')
a[a<0] = 1 
print(f'the product of all elements in array a(after replacement): {np.prod(a)}')

the product of all elements in array a: 2021760
the product of all elements in array a(after replacement): 1248


In [4]:
#Create a numpy array a of shape (5,6) with random values. Reshape the array into a new shape of (2,3,5). 
#Then, find the product of all the elements along the third axis

In [37]:
a = np.random.rand(5,6)
print(a)
b = a.reshape(2,3,5)
print(b)
print(f'the product of all the elements along the third axis: {np.prod(b, axis=2)}')

[[0.85700625 0.26805963 0.80656841 0.60381134 0.94060561 0.17623331]
 [0.74917952 0.20002779 0.92972008 0.51723828 0.72329085 0.91798582]
 [0.35947091 0.24088855 0.48963201 0.63911012 0.25082447 0.37979606]
 [0.05423441 0.97684253 0.65435121 0.69133821 0.27928777 0.64337596]
 [0.5534224  0.9843138  0.5080779  0.9748266  0.81477398 0.84686197]]
[[[0.85700625 0.26805963 0.80656841 0.60381134 0.94060561]
  [0.17623331 0.74917952 0.20002779 0.92972008 0.51723828]
  [0.72329085 0.91798582 0.35947091 0.24088855 0.48963201]]

 [[0.63911012 0.25082447 0.37979606 0.05423441 0.97684253]
  [0.65435121 0.69133821 0.27928777 0.64337596 0.5534224 ]
  [0.9843138  0.5080779  0.9748266  0.81477398 0.84686197]]]
the product of all the elements along the third axis: [[0.10523627 0.0127001  0.02815131]
 [0.00322549 0.04498575 0.33638841]]


# 15

In [5]:
#Given an array a and an array indices, replace the elements at the specified indices with a given value val.

In [38]:
a = np.array([1, 2, 3, 4, 5])
indices = np.array([1, 3])
val = 10

# Replace elements of 'a' at specified indices with 'val'
np.put(a, indices, val)

print("Original Array:", np.array([1, 2, 3, 4, 5]))
print("Array after replacing elements at specified indices with 'val':", a)

Original Array: [1 2 3 4 5]
Array after replacing elements at specified indices with 'val': [ 1 10  3 10  5]


In [6]:
#Given an array a and a list of indices to be replaced with values from a separate array b, replace the elements of a at the specified indices with the corresponding values from b

In [39]:
a = np.array([1, 2, 3, 4, 5])
indices = [1, 3]
b = np.array([10, 20])

# Replace elements of 'a' at specified indices with values from 'b'
a[indices] = b

print("Original Array:", np.array([1, 2, 3, 4, 5]))
print("Array after replacing elements at specified indices with values from 'b':", a)

Original Array: [1 2 3 4 5]
Array after replacing elements at specified indices with values from 'b': [ 1 10  3 20  5]


# 16

In [7]:
#Given a 2D NumPy array arr, flatten the array and store the result in a new variable flat_arr. 
#Then, print the flattened array and its shape.

In [46]:
a = np.random.randint(1,11,(3,4))
print(a)
flat_arr = np.ravel(a)
print(flat_arr)
b = np.shape(flat_arr)
print(b)

[[7 9 7 6]
 [6 4 4 7]
 [2 9 7 6]]
[7 9 7 6 6 4 4 7 2 9 7 6]
(12,)


In [47]:
#Given a 2D NumPy array arr, flatten the array in column-major (Fortran-style) order and store the result 
#in a new variable flat_arr. Then, print the flattened array and its shape.

In [62]:
a = np.array([[1,2,3],
              [4,5,6]])
print(a)
flat_arr = np.ravel(a,'f')
print(f'flattened array: {flat_arr}')
print(f'shape of array: {np.shape(flat_arr)}')

[[1 2 3]
 [4 5 6]]
flattened array: [1 4 2 5 3 6]
shape of array: (6,)


# 17

In [9]:
#Given a 1D numpy array a of length n, write a function that creates a 2D numpy array b of shape (m, n)

In [66]:
a = np.array([1,2,3,4,5,6])
b = np.reshape(a,(2,3))
print(b)

[[1 2 3]
 [4 5 6]]


In [10]:
#Given a 1D numpy array a of length n, write a function to reshape a into a 2D numpy array of shape (sqrt(n), sqrt(n)).

In [85]:
a = np.arange(16)

def reshape_to_sqrt(a):
    n = len(a)
    sqrt_n = int(np.sqrt(n))
    return np.reshape(a, (sqrt_n, sqrt_n))

# 18

In [86]:
#Create a 2D NumPy array with dimensions (3,4).
#resize it to dimensions (5,6). Print the original and resized arrays.

In [94]:
#resizing means changing the original array!!!

a = np.random.randint(1,11,(3,4))
print(a)

b = np.resize(a,(5,6))
print(b)

[[10  4  2  4]
 [ 8  1  1  2]
 [ 8 10 10  6]]
[[10  4  2  4  8  1]
 [ 1  2  8 10 10  6]
 [10  4  2  4  8  1]
 [ 1  2  8 10 10  6]
 [10  4  2  4  8  1]]


In [12]:
#Create a 1D NumPy array of length 10 with random integers between 1 and 5.resize it to dimensions (2,5). 
#Print the original and resized arrays.

In [100]:
a = np.random.randint(1,6,10)
print(a)

b = np.resize(a,(2,5))
print(b)

[5 1 5 2 2 3 4 2 4 3]
[[5 1 5 2 2]
 [3 4 2 4 3]]


# 19

In [101]:
#Write a program that generates a random array between 0 and 10 and then rounds them to the nearest integer. 
#Print the original array and the rounded array.

In [111]:
a = np.random.uniform(0,11,10)
print(f'the original array: {a}')

b = np.round(a)
print(f'the rounded array: {b}')

the original array: [9.67827299 6.22841292 3.77381337 2.6973691  4.14279606 4.86542927
 2.61109831 2.48107355 1.47105294 3.07105358]
the rounded array: [10.  6.  4.  3.  4.  5.  3.  2.  1.  3.]


In [14]:
#Write a function that takes an array of float values and a rounding precision as input and returns the 
#array rounded to the specified precision

In [117]:
c = np.random.uniform(0,11,10)
print(f'the original array: {c}')

d = np.round(c,2)
print(f'the rounded array(,2): {b}')

the original array: [ 3.68959392  9.34009273  3.08485427  0.80043435  1.76707684  5.87569358
  0.0907189   4.48321688 10.75045092 10.83176141]
the rounded array(,2): [10.  6.  4.  3.  4.  5.  3.  2.  1.  3.]


# 20

In [15]:
#Sorting a 2D array: Create a 2D numpy array and sort its rows in ascending order. Then, sort its columns in descending order.

In [149]:
a = np.array([[1,11,8,3],
              [2,6,9,8]])
sort_rows = np.sort(a,axis=1)
sort_columns = np.sort(a,axis=0)[::-1]
print(f'sorted rows in ascenting order: {sort_rows}')
print(f'sorted columns in descending order: {sort_columns}')

sorted rows in ascenting order: [[ 1  3  8 11]
 [ 2  6  8  9]]
sorted columns in descending order: [[ 2 11  9  8]
 [ 1  6  8  3]]


In [151]:
#Sorting a structured array: Create a structured numpy array with fields name, age, and salary. 
#Sort the array first by salary in descending order, then by age in ascending order.

In [150]:
data = np.array([('John', 30, 50000),
                 ('Mary', 25, 60000),
                 ('Bob', 35, 40000),
                 ('Jane', 20, 55000)],
                dtype=[('name', 'U10'), ('age', int), ('salary', float)])
sorted_data = np.sort(data, order=('salary', 'age'), kind='quicksort')[::-1]
print(sorted_data)


[('Mary', 25, 60000.) ('Jane', 20, 55000.) ('John', 30, 50000.)
 ('Bob', 35, 40000.)]


# 21

In [17]:
#Calculate the standard deviation of the following set of numbers using NumPy: [10, 15, 18, 21, 12, 9, 7, 23].

In [153]:
a = np.array([10, 15, 18, 21, 12, 9, 7, 23])
stdev_a = np.std(a)
print(stdev_a)

5.475799028452378


In [19]:
#Find the standard deviation of the array 'a' with shape (5, 3).

In [161]:
b = np.random.uniform(5,3,6)
print(b)

stdev_b = np.std(b)
print(stdev_b)

[3.23619001 4.927422   4.98050894 4.17504504 4.21502373 3.70874069]
0.6203686650663751


In [20]:
#Given an array 'a' of shape (10, 5), calculate the standard deviation of the first and last columns (axis 0) 
#and report the results.

In [175]:
a = np.random.randint(1,101,(10,5))
print(a)

print(f'standard deviation of the 1st column: {np.std(a[:,0])}')
print(f'standard deviation of the 1st column: {np.std(a[:,-1])}')

[[24 26 18 35 63]
 [24 58 80 76 69]
 [53 33 42 60 49]
 [69 54 88 96 31]
 [31 10  9 97 12]
 [86 16 68 28 59]
 [92 49 38  8 70]
 [46  7 92 91 44]
 [41 95 11 97 59]
 [35  4 33 51 25]]
standard deviation of the 1st column: 23.3771255718063
standard deviation of the 1st column: 18.769389974104115


# 22

In [87]:
#Given a 2D numpy array arr, write a Python function to find the sum of all the elements in each column of 
#the array and return the result as a 1D numpy array.

In [177]:
a = np.random.randint(1,101,(4,5))
print(a)

sums = np.sum(a,axis=0)
print(sums)

[[38 16  4 57  1]
 [80  4 32  9 98]
 [77  2 85 52 51]
 [22 71 70 45 22]]
[217  93 191 163 172]


In [88]:
#Write a Python function that takes two 2D numpy arrays arr1 and arr2 of the same shape, and create
#a new array with the element-wise sum of the two input arrays.

In [187]:
arr1 = np.arange(12).reshape(3,4)
arr2 = np.random.randint(0,101,(3,4))
print(arr1)
print(arr2)

summarized = np.sum([arr1,arr2],axis=0)
print(summarized)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[86 32 64 97]
 [87 95 37 18]
 [35 79 13  7]]
[[ 86  33  66 100]
 [ 91 100  43  25]
 [ 43  88  23  18]]


# 23

In [89]:
#Create a 2D NumPy array of size 3x4 and transpose it. Print the original and transposed arrays.

In [188]:
arr1 = np.array([[1,2,3],
                 [4,5,6]])
arr2 = np.transpose(arr1)
print(arr1)
print(arr2)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


In [90]:
#Create a random 2D NumPy array of size 5x7 and transpose it. Calculate the mean of the original 
#and transposed arrays and print the results.

In [197]:
#obviously the results'll be same, but lets use 2 modules in one
a = np.random.randint(1,101,(5,7))

print(f'mean of 1st array: {np.mean(a)}')
print(f'mean of 2nd array: {np.transpose(a).mean()}')

mean of 1st array: 51.34285714285714
mean of 2nd array: 51.34285714285714


# 24

In [91]:
#Create a 2D array of shape (3, 4) filled with ones, and another 2D array of the 
#same shape filled with zeros. Display both arrays.

In [200]:
ones = np.ones((3,4))
zeros = np.zeros((3,4))

print(ones)
print(zeros)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [92]:
#Create a random 1D array of length 7 using np.random.rand, and then create 
#a new array of the same shape filled with zeros. Display both arrays.

In [205]:
arr1 = np.random.rand(7)
print(arr1)

arr2 = np.zeros_like(arr1)
print(arr2)

[0.78317137 0.66567771 0.20679808 0.19056577 0.14882172 0.77837374
 0.89926862]
[0. 0. 0. 0. 0. 0. 0.]


# 25

In [93]:
#Create an array of all even numbers between 10 and 30

In [208]:
a = np.arange(10,31,2)
print(a)

[10 12 14 16 18 20 22 24 26 28 30]


In [94]:
# create an array of length 10 with values ranging from 0 to 1 (exclusive).

In [210]:
arr = np.arange(0,1,0.1)
print(arr)

[0]


In [216]:
#Create an array with values ranging from 0 to 10 (inclusive) with a step size of 0.33

In [215]:
a = np.arange(0,11,0.33)
print(a)

[ 0.    0.33  0.66  0.99  1.32  1.65  1.98  2.31  2.64  2.97  3.3   3.63
  3.96  4.29  4.62  4.95  5.28  5.61  5.94  6.27  6.6   6.93  7.26  7.59
  7.92  8.25  8.58  8.91  9.24  9.57  9.9  10.23 10.56 10.89]


# 26

In [96]:
#Create two arrays of the same size and concatenate them horizontally

In [14]:
arr1 = np.arange(20).reshape(4,5)
arr2 = np.arange(20,40).reshape(4,5)
concatenate = np.hstack((arr1,arr2))
print(concatenate)

[[ 0  1  2  3  4 20 21 22 23 24]
 [ 5  6  7  8  9 25 26 27 28 29]
 [10 11 12 13 14 30 31 32 33 34]
 [15 16 17 18 19 35 36 37 38 39]]


In [97]:
#Create a 2D array of shape (3, 3) and a 2D array of shape (3, 2). Concatenate them VERTICALLY

In [33]:
arr1 = np.arange(9).reshape(3,3)
arr2 = np.arange(9,15).reshape(2,3)

concatenate = np.vstack((arr1,arr2))
print(concatenate)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [98]:
#Create three arrays of the same shape and concatenate them along the first axis. 
#Then, sort the resulting array along the second axis

In [48]:
arr1 = np.random.randint(0,12,(4,3))
arr2 = np.random.randint(12,24,(4,3))
arr3 = np.random.randint(24,36,(4,3))

concatenate = np.hstack((arr1,arr2,arr3))
concatenate.sort(axis=1)
print(concatenate)

[[ 4  4  7 16 19 21 31 31 32]
 [ 3  3  8 15 19 23 24 24 33]
 [ 0  1  8 13 16 22 33 34 35]
 [ 8 11 11 14 14 23 24 25 27]]


In [99]:
#Create two arrays with shape (2, 3) and concatenate them vertically

In [100]:
#Create two arrays with shape (3, 2) and concatenate them horizontally

In [101]:
#Create two arrays with different shapes and try to concatenate them vertically

# 28

In [102]:
#Create a 6x6 identity matrix

In [53]:
identity = np.eye(6,6)
print(identity)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


In [104]:
#Create a 7x7 matrix with a specified number of ones above and below the diagonal

In [54]:
# Number of ones above and below the diagonal
num_ones = 2

# Create a 7x7 matrix with the specified number of ones
matrix = np.eye(7, k=num_ones) + np.eye(7, k=-num_ones)

# Print the matrix
print(matrix)

[[0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]]


In [105]:
#Create a 2D array with zeros everywhere except for the second diagonal below the main diagonal

In [59]:
a = np.eye(6,6,k = -1)
print(a)

[[0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]]


# 29

In [106]:
#Given a 2D NumPy array, find the number of unique values in each row and return them as a 1D array.

In [74]:
arr = np.random.randint(1,10,10).reshape(2,5)
print(arr)
uniq = np.unique(arr)
print(uniq)

[[2 4 9 8 2]
 [7 8 9 9 2]]
[2 4 7 8 9]


In [107]:
#Given a 1D NumPy array, find the unique values and their counts.

In [75]:
# Generate a 1D NumPy array with random integers between 1 and 10
arr = np.random.randint(1, 11, size=10)
print(arr)

# Find the unique values and their counts
unique_values, unique_counts = np.unique(arr, return_counts=True)
print("Unique Values:", unique_values)
print("Unique Counts:", unique_counts)

[ 3  2  1  1  1 10  5  8  9  1]
Unique Values: [ 1  2  3  5  8  9 10]
Unique Counts: [4 1 1 1 1 1 1]


# 30

In [108]:
#Given two arrays, a and b, create a new array c where each element is a if the corresponding element 
#in b is greater than 0, and b otherwise.

In [85]:
a = np.random.randint(-6,7,(4,3))
b = np.random.randint(-4,9,(4,3))

c = np.where(b>0, a, b)
print(c)

[[ 3 -1 -5]
 [-5  0 -6]
 [ 4 -5 -6]
 [-2 -4  0]]


In [109]:
#Generate a random 2D array with values between 0 and 1. create a new array where elements 
#greater than 0.5 are replaced with 1 and elements less than or equal to 0.5 are replaced with 0.

In [90]:
arr1 = np.random.rand(3,4)
print(arr1)

arr2 = np.where(arr1>0.5,1,0)
print(arr2)

[[0.43526909 0.75323035 0.36088043 0.97906746]
 [0.74448203 0.70024568 0.22838091 0.854095  ]
 [0.70448346 0.76285768 0.20280903 0.62548481]]
[[0 1 0 1]
 [1 1 0 1]
 [1 1 0 1]]


# 31

In [110]:
#Given an array of size 3x3, create a new array that is a mirror image of the original array along the horizontal axis.

In [92]:
a = np.arange(9).reshape(3,3)
mirr = np.flip(a,axis=1)
print(mirr)

[[2 1 0]
 [5 4 3]
 [8 7 6]]


In [111]:
#reate a random array of integers between 1 and 100 of size 4x4. create a new array that is a mirror 
#image of the original array along the vertical axis.

In [95]:
arr = np.random.randint(1,101,(4,4))
print(arr)
mirr = np.flip(arr,axis=0)
print(mirr)

[[73 91 33 46]
 [92 65 70 70]
 [44 43  3  8]
 [56 16  2 31]]
[[56 16  2 31]
 [44 43  3  8]
 [92 65 70 70]
 [73 91 33 46]]


# 32

In [112]:
#Given a square matrix, create an array that contains the diagonal elements of the matrix.

In [110]:
a = np.arange(25).reshape(5,5)
print(a)
diag = np.diagonal(a)
print(diag)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[ 0  6 12 18 24]


In [113]:
#Create a random array of integers between 1 and 100 of size 5x5. create an array that contains 
#the diagonal elements of the matrix.

In [112]:
arr = np.random.randint(1,101,(5,5))
print(arr)
diag = np.diagonal(arr)
print(diag)

[[ 5 15 89 86 57]
 [82 60 60 70 90]
 [72 15 84 42 76]
 [79 15 88 45 85]
 [70 10 73 85 37]]
[ 5 60 84 45 37]


# 34

In [113]:
#Generate a 1D array of length 50 with random values following a normal distribution with 
#mean 10 and standard deviation 2

In [ ]:
# Generate a 1D array of length 50 with random values following a normal distribution with mean 10 and standard deviation 2
a = np.random.normal(10, 2, size=50)
print(a)

# 35

In [117]:
#Create a 4x4 matrix with random integer values between 1 and 10 and then randomly choose 3 elements from the matrix

In [123]:
matrix = np.random.randint(1, 11, size=(4, 4))
print(matrix)

# Randomly choose 3 elements from the matrix
chosen_elements = np.random.choice(matrix.flatten(), size=3, replace=False)
print(chosen_elements)

[[ 9  6  9  2]
 [ 4 10  5  4]
 [ 8  1  1 10]
 [ 9  7  5  4]]
[9 4 5]


In [118]:
#Generate a 3x3 matrix with values between 0 and 1 and shuffle

In [133]:
a = np.random.rand(3,3)
np.random.shuffle(a)
print(a)

[[0.9880133  0.9483035  0.46571478]
 [0.58162876 0.8170412  0.59510042]
 [0.8564543  0.72759476 0.81236791]]
